export default [
  {
    path: '/user',
    layout: false,
    routes: [{
      path: '/user',
      routes: [{
        name: 'login',
        path: '/user/login',
        component: './user/Login',
      }],
    },
      {
        component: './404',
      },
    ],
  },
  {
    path: '/personalcenter',
    name: '个人中心',
    icon: 'user',
    routes: [
      {
        path: '/personalcenter',
        redirect: '/personalcenter/todo/approval',
      },
      {
        name: '待办任务',
        icon: 'profile',
        path: '/personalcenter/todo',
        component: './contract/person/todo',
        access: 'hasRoute',
        routes: [
          {
            path: '/personalcenter/todo',
            redirect: '/personalcenter/todo/approval',
          },
          {
            name: '待审批的合同',
            path: '/personalcenter/todo/approval',
            component: './contract/person/todo/approval',
            access: 'hasRoute',
          },
          {
            name: '待修订的合同',
            path: '/personalcenter/todo/revise',
            component: './contract/person/todo/revise',
            access: 'hasRoute',
          },
          {
            component: './404',
          },
        ],
      },
      {
        name: '已办任务',
        icon: 'fileDone',
        path: '/personalcenter/done',
        component: './Welcome',
        access: 'hasRoute',
      },
      {
        name: '承揽方收藏',
        icon: 'bank',
        path: '/personalcenter/perToContractor',
        component: './contract/person/perToContractor',
        access: 'hasRoute',
      },
      {
        name: '模版收藏',
        icon: 'solution',
        path: '/personalcenter/perToTemplate',
        component: './contract/person/perToTemplate',
        access: 'hasRoute',
      },
      {
        name: '审批常用语',
        icon: 'solution',
        path: '/personalcenter/approvalOpinions',
        component: './contract/person/approvalOpinions',
        access: 'hasRoute',
      },
      {
        name: '修改密码',
        icon: 'edit',
        path: '/personalcenter/updatePass',
        component: './contract/person/password',
        hideInMenu: true
      },
      {
        component: './404',
      },
    ],
  },
  {
    path: '/business',
    name: '业务中心',
    icon: 'desktop',
    access: 'hasRoute',
    routes: [
      {
        path: '/business',
        component: './Welcome',
      },
      {
        name: '定作方管理',
        icon: 'team',
        path: '/business/sponsor',
        component: './contract/business/sponsor',
        access: 'hasRoute',
      },
      {
        name: '承揽方管理',
        icon: 'team',
        path: '/business/contractor',
        component: './contract/business/contractor',
        access: 'hasRoute',
      },
      {
        name: '专业管理',
        icon: 'team',
        path: '/business/major',
        component: './contract/business/major',
        access: 'hasRoute',
      },
      {
        name: '模板类型管理',
        icon: 'container',
        path: '/business/templateType',
        component: './contract/business/templateType',
        access: 'hasRoute',
      }, {
        name: '专业对应角色管理',
        icon: 'team',
        path: '/business/majorToRole',
        component: './contract/business/majorToRole',
        access: 'hasRoute',
      },
      {
        name: '专业对应流程管理',
        icon: 'team',
        path: '/business/majorToFlow',
        component: './contract/business/majorToFlow',
        access: 'hasRoute',
      },
      {
        name: '模板管理',
        icon: 'container',
        path: '/business/template',
        component: './contract/business/template',
        access: 'hasRoute',
      },
      {
        name: '模板下载',
        icon: 'container',
        path: '/business/templateDown',
        component: './contract/business/templateDown',
        access: 'hasRoute',
      },
      {
        name: '管理流程定义',
        icon: 'team',
        path: '/business/processDefinition',
        component: './contract/business/processDefinition',
        access: 'hasRoute',
      },
      {
        name: '合同审查',
        icon: 'team',
        path: '/business/review',
        component: './contract/business/processDefinition',
        access: 'hasRoute',
      },
      {
        name: '合同履行',
        icon: 'team',
        path: '/business/perform',
        component: './contract/business/processDefinition',
        access: 'hasRoute',
      },
      {
        name: '合同编制',
        icon: 'team',
        path: '/business/contractPreparation',
        component: './contract/business/contractPreparation',
        access: 'hasRoute',
      },
      {
        component: './404',
      },
    ],
  },
  {
    path: '/system',
    name: '系统设置',
    icon: 'setting',
    access: 'hasRoute',
    routes: [
      {
        path: '/system',
        component: './Welcome',
      },
      {
        name: '字典管理',
        icon: 'book',
        path: '/system/dictionary',
        component: './contract/common/dictionary',
        access: 'hasRoute',
      },
      {
        name: '人员管理',
        icon: 'team',
        path: '/system/person',
        component: './contract/common/person',
        access: 'hasRoute',
      },
      {
        name: '菜单管理',
        icon: 'bars',
        path: '/system/menu',
        component: './contract/common/menu',
        access: 'hasRoute',
      },
      {
        name: '岗位管理',
        icon: 'audit',
        path: '/system/post',
        component: './contract/common/post',
        access: 'hasRoute',
      },
      {
        name: '角色管理',
        icon: 'user',
        path: '/system/role',
        component: './contract/common/role',
        access: 'hasRoute',
      },
      {
        name: '组织机构管理',
        icon: 'team',
        path: '/system/dept',
        component: './contract/common/dept',
        access: 'hasRoute',
      },
      {
        name: '日志管理',
        icon: 'container',
        path: '/system/log',
        access: 'hasRoute',
        routes: [
          {
            name: '操作日志',
            icon: 'container',
            path: '/system/log/operlog',
            access: 'hasRoute',
            component: './contract/common/log',
          },
          {
            name: '登录日志',
            icon: 'container',
            path: '/system/log/loginLog',
            access: 'hasRoute',
            component: './contract/common/loginLog',
          },
          {
            component: './404',
          },
        ],
      },
      {
        name: '机构人员岗位管理',
        icon: 'user',
        path: '/system/personToPost',
        component: './contract/common/personToPost',
        access: 'hasRoute',
      },
      {
        name: '机构人员角色管理',
        icon: 'user',
        path: '/system/perToRole',
        component: './contract/common/perToRole',
        access: 'hasRoute',
      },
      {
        name: '机构人员菜单管理',
        icon: 'user',
        path: '/system/personToMenu',
        component: './contract/common/personToMenu',
        access: 'hasRoute',
      },
      {
        name: '角色菜单管理',
        icon: 'user',
        path: '/system/roleToMenu',
        component: './contract/common/roleToMenu',
        access: 'hasRoute',
      },
      {
        name: '文件上传',
        icon: 'file',
        path: '/system/fileUpload',
        component: './contract/common/fileUpload',
        access: 'hasRoute',
      },
      {
        name: '系统监控',
        icon: 'container',
        path: '/system/monitor',
        access: 'hasRoute',
        routes: [
          {
            name: '数据监控',
            icon: 'container',
            path: '/system/monitor/druid',
            access: 'hasRoute',
            component: './contract/common/monitor/druid',
          },
          {
            name: '服务监控',
            icon: 'container',
            path: '/system/monitor/service',
            access: 'hasRoute',
            component: './contract/common/monitor/service',
          },
          {
            component: './404',
          },
        ],
      },
      {
        component: './404',
      },
    ],
  },
  {
    path: '/',
    //redirect: '/personalcenter/todo',
    component: './Welcome',
  },
  {
    component: './404',
  },
];
