import {
  AuditOutlined,
  BankOutlined,
  BarsOutlined,
  BookOutlined,
  ContainerOutlined,
  CrownOutlined,
  DesktopOutlined,
  DownloadOutlined,
  EditOutlined,
  FileDoneOutlined,
  FileOutlined,
  FormOutlined,
  HomeOutlined,
  MonitorOutlined,
  PartitionOutlined,
  PrinterOutlined,
  ProfileOutlined,
  ReconciliationOutlined,
  SafetyCertificateOutlined,
  SearchOutlined,
  SettingOutlined,
  SmileOutlined,
  SolutionOutlined,
  StarOutlined,
  TableOutlined,
  TeamOutlined,
  ToolOutlined,
  UploadOutlined,
  UserOutlined,
  WalletOutlined
} from "@ant-design/icons/lib";
import React from "react";

export const iconMap = {
  profile: <ProfileOutlined/>,
  fileDone: <FileDoneOutlined/>,
  bank: <BankOutlined/>,
  table: <TableOutlined/>,
  smile: <SmileOutlined/>,
  crown: <CrownOutlined/>,
  container: <ContainerOutlined/>,
  audit: <AuditOutlined/>,
  bars: <BarsOutlined/>,
  desktop: <DesktopOutlined/>,
  download: <DownloadOutlined/>,
  team: <TeamOutlined/>,
  book: <BookOutlined/>,
  setting: <SettingOutlined/>,
  user: <UserOutlined/>,
  tool: <ToolOutlined/>,
  safetyCertificate: <SafetyCertificateOutlined/>,
  home: <HomeOutlined/>,
  edit: <EditOutlined/>,
  file: <FileOutlined/>,
  wallet: <WalletOutlined/>,
  monitor: <MonitorOutlined/>,
  partition: <PartitionOutlined/>,
  solution: <SolutionOutlined/>,
  upload: <UploadOutlined/>,
  star: <StarOutlined/>,
  search: <SearchOutlined/>,
  reconciliation: <ReconciliationOutlined/>,
  printer: <PrinterOutlined/>,
  form: <FormOutlined/>,
};

//icon下拉框
export const iconOpinion = [
  {value: 'audit', label: 'audit'},
  {value: 'bank', label: 'bank'},
  {value: 'bars', label: 'bars'},
  {value: 'book', label: 'book'},
  {value: 'container', label: 'container'},
  {value: 'crown', label: 'crown'},
  {value: 'desktop', label: 'desktop'},
  {value: 'download', label: 'download'},
  {value: 'edit', label: 'edit'},
  {value: 'file', label: 'file'},
  {value: 'fileDone', label: 'fileDone'},
  {value: 'form', label: 'form'},
  {value: 'home', label: 'home'},
  {value: 'monitor', label: 'monitor'},
  {value: 'partition', label: 'partition'},
  {value: 'printer', label: 'printer'},
  {value: 'profile', label: 'profile'},
  {value: 'reconciliation', label: 'reconciliation'},
  {value: 'safetyCertificate', label: 'safetyCertificate'},
  {value: 'search', label: 'search'},
  {value: 'setting', label: 'setting'},
  {value: 'smile', label: 'smile'},
  {value: 'solution', label: 'solution'},
  {value: 'star', label: 'star'},
  {value: 'table', label: 'table'},
  {value: 'team', label: 'team'},
  {value: 'tool', label: 'tool'},
  {value: 'upload', label: 'upload'},
  {value: 'user', label: 'user'},
  {value: 'wallet', label: 'wallet'},
];
