import {
  AuditOutlined,
  BankOutlined,
  BarsOutlined,
  BookOutlined,
  CommentOutlined,
  ContainerOutlined,
  CrownOutlined,
  DesktopOutlined,
  DownloadOutlined,
  EditOutlined,
  FileDoneOutlined,
  FileOutlined,
  FormOutlined,
  HomeOutlined,
  MenuOutlined,
  MessageOutlined,
  MonitorOutlined,
  PartitionOutlined,
  PrinterOutlined,
  ProfileOutlined,
  ReadOutlined,
  ReconciliationOutlined,
  SafetyCertificateOutlined,
  SearchOutlined,
  SettingOutlined,
  SmileOutlined,
  SolutionOutlined,
  StarOutlined,
  TableOutlined,
  TeamOutlined,
  ToolOutlined,
  UploadOutlined,
  UserOutlined,
  WalletOutlined
} from "@ant-design/icons/lib";
import React from "react";
import MenuIcon from "@/components/Icons/MenuIcon";
import DeptIcon from "@/components/Icons/DeptIcon";
import RoleIcon from "@/components/Icons/RoleIcon";
import LogIcon from "@/components/Icons/LogIcon";
import LoginLogIcon from "@/components/Icons/LoginLogIcon";
import MajorIcon from "@/components/Icons/MajorIcon";
import SponsorIcon from "@/components/Icons/SponsorIcon";
import ContractIcon from "@/components/Icons/ContractIcon";

export const iconMap = {
  profile: <ProfileOutlined/>,
  fileDone: <FileDoneOutlined/>,
  bank: <BankOutlined/>,
  table: <TableOutlined/>,
  smile: <SmileOutlined/>,
  crown: <CrownOutlined/>,
  container: <ContainerOutlined/>,
  audit: <AuditOutlined/>,
  bars: <BarsOutlined/>,
  desktop: <DesktopOutlined/>,
  download: <DownloadOutlined/>,
  team: <TeamOutlined/>,
  book: <BookOutlined/>,
  setting: <SettingOutlined/>,
  user: <UserOutlined/>,
  tool: <ToolOutlined/>,
  safetyCertificate: <SafetyCertificateOutlined/>,
  home: <HomeOutlined/>,
  edit: <EditOutlined/>,
  file: <FileOutlined/>,
  wallet: <WalletOutlined/>,
  monitor: <MonitorOutlined/>,
  partition: <PartitionOutlined/>,
  solution: <SolutionOutlined/>,
  upload: <UploadOutlined/>,
  star: <StarOutlined/>,
  search: <SearchOutlined/>,
  reconciliation: <ReconciliationOutlined/>,
  printer: <PrinterOutlined/>,
  form: <FormOutlined/>,
  menu: <MenuOutlined/>,
  message: <MessageOutlined/>,
  comment: <CommentOutlined/>,
  read: <ReadOutlined/>,
  menus: <MenuIcon/>,
  dept: <DeptIcon/>,
  role: <RoleIcon/>,
  log: <LogIcon/>,
  loginLog: <LoginLogIcon/>,
  major: <MajorIcon/>,
  sponsor: <SponsorIcon/>,
  contract: <ContractIcon/>,
};

//icon下拉框
export const iconOpinion = [
  {value: 'audit', label: iconMap['audit']},
  {value: 'bank', label: iconMap['bank']},
  {value: 'bars', label: iconMap['bars']},
  {value: 'book', label: iconMap['book']},
  {value: 'comment', label: iconMap['comment']},
  {value: 'container', label: iconMap['container']},
  {value: 'crown', label: iconMap['crown']},
  {value: 'desktop', label: iconMap['desktop']},
  {value: 'download', label: iconMap['download']},
  {value: 'edit', label: iconMap['edit']},
  {value: 'file', label: iconMap['file']},
  {value: 'fileDone', label: iconMap['fileDone']},
  {value: 'form', label: iconMap['form']},
  {value: 'home', label: iconMap['home']},
  {value: 'menu', label: iconMap['menu']},
  {value: 'message', label: iconMap['message']},
  {value: 'monitor', label: iconMap['monitor']},
  {value: 'partition', label: iconMap['partition']},
  {value: 'printer', label: iconMap['printer']},
  {value: 'profile', label: iconMap['profile']},
  {value: 'reconciliation', label: iconMap['reconciliation']},
  {value: 'safetyCertificate', label: iconMap['safetyCertificate']},
  {value: 'search', label: iconMap['search']},
  {value: 'setting', label: iconMap['setting']},
  {value: 'smile', label: iconMap['smile']},
  {value: 'solution', label: iconMap['solution']},
  {value: 'star', label: iconMap['star']},
  {value: 'table', label: iconMap['table']},
  {value: 'team', label: iconMap['team']},
  {value: 'tool', label: iconMap['tool']},
  {value: 'upload', label: iconMap['upload']},
  {value: 'user', label: iconMap['user']},
  {value: 'wallet', label: iconMap['wallet']},
  {value: 'read', label: iconMap['read']},
  {value: 'menus', label: iconMap['menus']},
  {value: 'dept', label: iconMap['dept']},
  {value: 'role', label: iconMap['role']},
  {value: 'log', label: iconMap['log']},
  {value: 'loginLog', label: iconMap['loginLog']},
  {value: 'major', label: iconMap['major']},
  {value: 'sponsor', label: iconMap['sponsor']},
  {value: 'contract', label: iconMap['contract']},
];
